spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security_auth
spring.datasource.username=surmanikonsam
spring.datasource.password=databaseDesigner

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port = 8080
logging.level.org.springframework.web=DEBUG